import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
} from "@clerk/nextjs";
import { AppProps } from "next/app";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider proxyUrl={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
      <SignedOut>
        <html>
          <body>
            <SignInButton />
          </body>
        </html>
      </SignedOut>
      <SignedIn>
        <html>
          <body>{children}</body>
        </html>
      </SignedIn>
    </ClerkProvider>
  );
}
